name: CI
on: [pull_request]

jobs:
  test-legacy:
    runs-on: self-hosted
    env:
      ImageOS: ubuntu18
    strategy:
      matrix:
        elixir: ["1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10", "1.11"]
        otp: ["19", "20", "21", "22", "23"]
        exclude:
          - elixir: "1.4"
            otp: "20"
          - elixir: "1.4"
            otp: "21"
          - elixir: "1.4"
            otp: "22"
          - elixir: "1.4"
            otp: "23"
          - elixir: "1.5"
            otp: "21"
          - elixir: "1.5"
            otp: "22"
          - elixir: "1.5"
            otp: "23"
          - elixir: "1.6"
            otp: "21"
          - elixir: "1.6"
            otp: "22"
          - elixir: "1.6"
            otp: "23"
          - elixir: "1.7"
            otp: "23"
          - elixir: "1.8"
            otp: "19"
          - elixir: "1.8"
            otp: "23"
          - elixir: "1.9"
            otp: "19"
          - elixir: "1.9"
            otp: "23"
          - elixir: "1.10"
            otp: "19"
          - elixir: "1.10"
            otp: "20"
          - elixir: "1.11"
            otp: "19"
          - elixir: "1.11"
            otp: "20"
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '8.10.0'
      - uses: actions/checkout@v3
      - name: Setup Erlang/OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Install npm dependencies
        run: npm install
      - name: Install Elixir dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ["1.12", "1.13", "1.14", "1.15", "1.16", "1.17", "1.18"]
        otp: ["24", "25", "26", "27"]
        exclude:
          - elixir: "1.12"
            otp: "25"
          - elixir: "1.12"
            otp: "26"
          - elixir: "1.12"
            otp: "27"
          - elixir: "1.13"
            otp: "25"
          - elixir: "1.13"
            otp: "26"
          - elixir: "1.13"
            otp: "27"
          - elixir: "1.14"
            otp: "26"
          - elixir: "1.14"
            otp: "27"
          - elixir: "1.15"
            otp: "27"
          - elixir: "1.16"
            otp: "27"
          - elixir: "1.17"
            otp: "24"
          - elixir: "1.18"
            otp: "24"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Erlang/OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Install npm dependencies
        run: npm install
      - name: Install Elixir dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
